name: CI
on:
    push:
        branches:
            - default
jobs:
    split-upm:
        name: split upm branch
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v3 # specify the version to v3
              with:
                  fetch-depth: 0
            - name: split upm branch
              run: |
                  git subtree split -P "$PKG_ROOT" -b upm
                  git push -u origin upm
              env:
                  PKG_ROOT: com.tsk.ide.vscode
